org: kepennar
app: myapp-dev
service: pdfator

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 1536
  timeout: 180
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

package:
  artifact: ./package.zip
  individually: true

functions:
  pdfator:
    handler: index.pdfatorHandler
    events:
      - http:
          path: /
          method: get
          cors: true
    environment:
      DEBUG: "true"
      BUCKET: ${self:custom.bucket}
      S3_PREFIX: ${self:custom.s3Prefix}

resources:
  Resources:
    S3BucketPdfatorScreens:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
        AccessControl: PublicRead
        # Set the CORS policy
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - HEAD
              MaxAge: 3000
        LifecycleConfiguration:
          Rules:
            - Id: ScreenExpiration
              Status: Enabled
              ExpirationInDays: 1

    S3BucketPdfatorScreensPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: S3BucketPdfatorScreens
        PolicyDocument:
          Statement:
            - Action:
                - s3:GetObject
              Effect: Allow
              Resource:
                - arn:aws:s3:::${self:custom.bucket}/*
              Principal: "*"

custom:
  bucket: pdfator-screens
  region: eu-west-3
  stage: test
  s3Prefix: screen
